'use strict'

const STORIES_CACHE_KEY = 'TOP_STORIES'

const STORY_CACHE_KEY = 'STORY_'

const STORIES_TTL = 60 * 5 // 5 min
const COMMENTS_TTL = 60 * 10 // 5 min

const STORIES_PER_PAGE = 20

const STORIES_COMMENTS_CACHE_KEY = 'STORIES_COMMENTS_'

module.exports = {
  STORIES_CACHE_KEY,
  STORY_CACHE_KEY,
  STORIES_TTL,
  STORIES_PER_PAGE,
  STORIES_COMMENTS_CACHE_KEY,
  COMMENTS_TTL
}
